services:
  brixtlanding:
    # Use your Docker image name here
    image: goswamirohit/brixtalanding:v1
    container_name: brixtalanding
    restart: unless-stopped
    ports:
      - "55000:3000"

    env_file:
      - .env.production
      